### ISSUE TITLE
Кастомизация интерфейса

### ISSUE THREAD

**Issue by vladislav805** [APIdogRU/6.6-issues#23]
https://apidog.ru/6..6/#settings?act=style
- [x] Прикрутить нормальный красивый выбиратель цвета
- [x] Выбор ширины страницы: small/legacy (как было на 6.4), medium (как сейчас), wide (~1400px).
- [x] Выбор размера шрифта.
- [x] Выбор высоты просмоторщика изображений (#48)

**Comment by Mishin870** [comment]
Возможно оффтоп, но не хватает размера шрифта (базового или множителя для всех частей интерфейса) и настройки картинок (в новой версии одиночное изображение в постах отображается мелко из-за ограничения высоты, если у него преобладает высота, даже на десктопе. и картинки в целом стали меньше на 1366х768)

_P.S. с помощью tampermonkey переопределяю_ `.preview-attach img{max-height:80vh!important}`
