### ISSUE TITLE
Время размещения поста в ленте "вчера" некорректно 

### ISSUE THREAD

**Issue by Andro173** [APIdogRU/6.6-issues#45]
Размещённый в ленте пост позавчера или даже два дня назад отображается, как вчера (время верное).
Похоже все июньские посты отображаются, как "вчера".

**Comment by vladislav805** [comment]
Уже исправлено было день назад, вроде. Проверьте, пожалуйста, предварительно очистив **кэш**.

**Comment by vladislav805** [comment]
Да, точно, был баг.
