### ISSUE TITLE
Кнопка "undefined" в черном списке

### ISSUE THREAD

**Issue by TheMicrosoftMan** [APIdogRU/6.6-issues#46]
Под каждым аккаунтом в черном списке (Settings -> Blacklist) есть кнопка "undefined". При клике на нее ничего не происходит.
![image](https://user-images.githubusercontent.com/40963479/83866601-b24ed100-a730-11ea-8a96-074f0fdc18c9.png)

**Comment by vladislav805** [comment]
Остались какие-то тестовые ноды.. Забыл убрать. Спасибо.
