### ISSUE TITLE
Переписать back/front-end авторизации

### ISSUE THREAD

**Issue by vladislav805** [APIdogRU/6.6-issues#71]
На данный момент авторизация происходит через код версии 6.4.x.

**Comment by BoberMod** [comment]
Нет кнопки отправки СМС для 2FA при нажатии на Enter после ввода логина-пароля.

1. Зайди на [auth](https://apidog.ru/auth.php)
2. Ввести логин и пароль от аккаунта с включенным 2FA по СМС.
3. Нажать Enter.

Актуальный результат: кнопка "Отправить код" не появляется. Поля для ввода кода нет.
Ожидаемый результат: кнопка с предложением отправить СМС.

Возможно, тоже самое и с 2FA через приложение - нет поля для ввода кода.

**Comment by vladislav805** [comment]
@BoberMod, при том, что это 6.4, не вижу смысла это фиксить, если страница логина будет переписана с нуля без этих багов (но будут другие).
